# Generated by Django 4.0.6 on 2022-09-04 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("iubase_players", "0002_rename_photos_photo_alter_transaction_date_announced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date_announced",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
