# Generated by Django 4.1 on 2022-09-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "iubase_players",
            "0005_alter_academic_degree_date_alter_article_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="academic",
            name="degree_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="headshot",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="bats",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="player",
            name="birthdate",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="height",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="hometown",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="middle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="throws",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="playersocial",
            name="handle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teamsocial",
            name="handle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="draft_round",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="jersey",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="position",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iubase_players.position",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="team",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iubase_players.team",
            ),
        ),
    ]
