# Generated by Django 4.1 on 2022-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iubase_players', '0007_alter_transaction_pro_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='draft_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='jersey',
            field=models.IntegerField(null=True),
        ),
    ]
