# Generated by Django 4.1 on 2022-09-04 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("iubase_players", "0008_alter_transaction_draft_round_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academic",
            name="degree_level",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="academic",
            name="major",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="accolade",
            name="organization",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="accolade",
            name="year",
            field=models.IntegerField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="league",
            name="description",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="level",
            name="description",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="photo",
            name="credit",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="photo",
            name="url",
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="country",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="first",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="hometown",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="last",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="middle",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="state",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="playersocial",
            name="url",
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="team",
            name="city",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="team",
            name="country",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iubase_players.league",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="team",
            name="state",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="teamsocial",
            name="url",
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="draft_round",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="jersey",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="pro_org",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="description",
            field=models.CharField(max_length=30),
        ),
    ]
