# Generated by Django 3.1.3 on 2020-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "sub_title",
                    models.CharField(blank=True, default=None, max_length=100),
                ),
                (
                    "location",
                    models.CharField(default="BLOOMINGTON, IN", max_length=100),
                ),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("featured_image", models.URLField(blank=True, null=True)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("flat_rate", models.BooleanField(default=False)),
                ("price", models.FloatField(blank=True, default=40.0, null=True)),
            ],
        ),
    ]
