# Generated by Django 3.1.3 on 2020-11-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("j34main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="author",
            field=models.CharField(default="Carl James", max_length=100),
        ),
    ]
