# Generated by Django 3.1.3 on 2020-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("j34main", "0002_content_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="teaser",
            field=models.TextField(default="change"),
            preserve_default=False,
        ),
    ]
