# Generated by Django 4.0.6 on 2022-07-15 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("j34main", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="j34main.category",
            ),
            preserve_default=False,
        ),
    ]
