# Generated by Django 4.0.6 on 2022-07-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('j34main', '0007_remove_content_category_content_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
    ]
