# Generated by Django 4.0.6 on 2022-07-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("j34main", "0008_remove_content_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="categories",
            field=models.ManyToManyField(to="j34main.category"),
        ),
    ]
