# Generated by Django 4.2.7 on 2023-12-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('j34main', '0009_content_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
